#!/bin/bash
set -euo pipefail

# Sync a committed bundle, retaining unrelated plugins, skills, and registrations.
# Usage: sync-skills-from-back.sh /path/to/back --ref FULL_SHA [--output DIR]
# --output must already exist. Use a temporary directory for release rehearsals.
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
exec python3 - "$SCRIPT_DIR/.." "$@" <<'PY'
import argparse
from collections import namedtuple
import contextlib
import json
import os
from pathlib import Path, PurePosixPath
import re
import shutil
import signal
import subprocess
import sys
import tarfile
import tempfile

SOURCE_PREFIX = "tools/cmd/macrodaemon/public-plugin"
REPOSITORY = "https://github.com/prassoai/macroscope-local"
LOCK_NAME = ".macroscope-sync.lock"
GENERATED_MARKER = "<!-- Generated by sync-skills-from-back.sh. -->"
PREREQ = """## 0. Verify the CLI is installed

```bash
command -v macroscope
```

If `macroscope` is not found, tell the user:

> Macroscope CLI is not installed. Install it with:
>
> ```bash
> curl -sSL https://raw.githubusercontent.com/prassoai/macroscope-local/main/install.sh | bash
> ```

Stop here if the CLI is missing.
"""

# relative: the destination below --output, walked one component at a time.
# candidate: the staged entry's name, replaced in from the transaction.
Target = namedtuple("Target", "relative candidate")


def fail(message):
    raise ValueError(message)


def git(repo, *arguments, **kwargs):
    # Caller worktree/index overrides must not change which repository is read.
    env = {key: value for key, value in os.environ.items() if not key.startswith("GIT_")}
    env["GIT_CONFIG_NOSYSTEM"] = "1"
    return subprocess.run(["git", "--no-optional-locks", "-C", str(repo), *arguments],
                          env=env, check=True, stderr=subprocess.PIPE, **kwargs)


def read_json(path):
    with path.open(encoding="utf-8") as stream:
        data = json.load(stream)
    if not isinstance(data, dict):
        fail(f"expected a JSON object: {path}")
    return data


def extract_source(repo, ref, stage):
    if not re.fullmatch(r"[0-9a-fA-F]{40}", ref):
        fail("--ref must be a full 40-character commit SHA")
    resolved = git(repo, "rev-parse", "--verify", ref + "^{commit}",
                   stdout=subprocess.PIPE, text=True).stdout.strip()
    if resolved != ref.lower():
        fail("--ref did not resolve to the requested commit")
    archive = stage / "source.tar"
    with archive.open("wb") as stream:
        git(repo, "archive", "--format=tar", resolved, "--", SOURCE_PREFIX, stdout=stream)
    root = stage / "source"
    root.mkdir()
    prefix = PurePosixPath(SOURCE_PREFIX).parts
    with tarfile.open(archive, "r:") as bundle:
        for member in bundle:
            name = PurePosixPath(member.name)
            if name.is_absolute() or ".." in name.parts:
                fail(f"unsafe source path: {member.name}")
            if name.parts == prefix[:len(name.parts)] and member.isdir():
                continue
            if name.parts[:len(prefix)] != prefix or not (member.isfile() or member.isdir()):
                fail(f"unsupported source archive entry: {member.name}")
            target = root.joinpath(*name.parts[len(prefix):])
            if member.isdir():
                target.mkdir(parents=True, exist_ok=True)
            else:
                target.parent.mkdir(parents=True, exist_ok=True)
                with bundle.extractfile(member) as source, target.open("xb") as dest:
                    shutil.copyfileobj(source, dest)
                target.chmod(0o755 if member.mode & 0o111 else 0o644)
    return root, resolved


def skill_frontmatter(path, name):
    lines = path.read_text(encoding="utf-8").splitlines(keepends=True)
    if not lines or lines[0].strip() != "---":
        fail(f"missing skill frontmatter: {path}")
    closing = next((i for i in range(1, len(lines)) if lines[i].strip() == "---"), None)
    if closing is None:
        fail(f"unterminated skill frontmatter: {path}")
    header = "".join(lines[1:closing])
    if not re.search(r"(?m)^name:\s*[\"']?" + re.escape(name) + r"[\"']?\s*$", header):
        fail(f"incorrect skill name: {path}")
    if not re.search(r"(?m)^description:\s*\S", header) or not "".join(lines[closing + 1:]).strip():
        fail(f"incomplete skill: {path}")
    return "".join(lines[:closing + 1]), "".join(lines[closing + 1:]).lstrip("\r\n")


def validate_bundle(root):
    plugin = root / "plugins/macroscope"
    marketplace = read_json(root / ".claude-plugin/marketplace.json")
    manifests = [read_json(plugin / host / "plugin.json")
                 for host in (".claude-plugin", ".codex-plugin", ".cursor-plugin")]
    version = manifests[0].get("version", "")
    if not isinstance(version, str) or not re.fullmatch(r"\d+\.\d+\.\d+(?:[-+][A-Za-z0-9.-]+)?", version):
        fail("plugin version must be a safe semantic version")
    if any(item.get("name") != "macroscope" or item.get("version") != version for item in manifests):
        fail("host plugin manifests disagree on name or version")
    entries = marketplace.get("plugins")
    if (marketplace.get("name") != "macroscope-local" or not isinstance(entries, list)
            or len(entries) != 1 or not isinstance(entries[0], dict)
            or entries[0].get("name") != "macroscope"
            or entries[0].get("source") != "./plugins/macroscope"
            or entries[0].get("version") != version):
        fail("source marketplace must match the Macroscope plugin and version")
    for relative in ("commands/macroscope-codereview.md", "commands/macroscope-autoloop.md",
                     "opencode/macroscope.js", "assets/macroscope.svg", "assets/macroscope-small.svg"):
        path = plugin / relative
        if not path.is_file() or path.stat().st_size == 0:
            fail(f"missing or empty plugin asset: {relative}")
    skills = sorted((plugin / "skills").iterdir())
    if not {"codereview", "autoloop"}.issubset({item.name for item in skills}):
        fail("source bundle must include codereview and autoloop skills")
    for skill in skills:
        if not skill.is_dir() or not re.fullmatch(r"[a-z0-9][a-z0-9-]*", skill.name):
            fail(f"invalid skill directory: {skill}")
        skill_frontmatter(skill / "SKILL.md", skill.name)
    for host in ("claude", "codex"):
        for name in ("codereview", "autoloop"):
            skill_frontmatter(plugin / "host-overlays" / host / "skills" / name / "SKILL.md", name)
    return marketplace, skills, version


def check_target(output, target):
    # Advisory pre-flight only: a pathname cannot bind the inode that the later
    # rename resolves. apply_targets enforces the same rule with O_NOFOLLOW
    # directory descriptors, which a concurrent writer cannot redirect.
    for path in (target, *target.parents):
        if path == output:
            break
        if path.is_symlink():
            fail(f"refusing to replace or traverse a destination symlink: {path}")
        if path != target and path.exists() and not path.is_dir():
            fail(f"destination parent is not a directory: {path}")


def skill_ownership(path, name):
    # Which marker, if any, makes this destination ours to replace. Ownership is
    # the marker's position, not its presence anywhere in the file: a foreign
    # skill that merely quotes the prerequisite block is not ours. Anything we
    # cannot parse is somebody else's file, so ownership fails closed rather
    # than reporting our own well-formedness rules against a foreign skill.
    try:
        body = skill_frontmatter(path, name)[1]
    except (OSError, ValueError):
        return None
    if body.startswith(GENERATED_MARKER):
        return "generated"
    # Bundles written before the generated marker existed lead with PREREQ, and
    # the published checkout is still one of them, so that shape has to remain
    # recognizable for the one-time migration. It is reported separately, never
    # as ownership: shape is a weaker claim than a marker this script wrote, and
    # the caller decides whether it is enough.
    return "legacy" if body.startswith(PREREQ) else None


def prepare_targets(root, output, transaction, marketplace, skills, adopt_unmarked):
    staged = transaction / "staged"
    staged.mkdir()
    plugin_target = output / "plugins/macroscope"
    market_target = output / ".claude-plugin/marketplace.json"
    for target in (plugin_target, market_target, *(output / "skills" / skill.name for skill in skills)):
        check_target(output, target)
    if plugin_target.exists():
        existing = read_json(plugin_target / ".claude-plugin/plugin.json")
        if existing.get("name") != "macroscope" or existing.get("repository") != REPOSITORY:
            fail(f"unowned plugin destination: {plugin_target}")
    if market_target.exists():
        existing = read_json(market_target)
        if existing.get("name") != marketplace["name"] or not isinstance(existing.get("plugins"), list):
            fail(f"unowned marketplace destination: {market_target}")
        foreign = []
        for entry in existing["plugins"]:
            if not isinstance(entry, dict):
                fail(f"invalid existing marketplace entry: {market_target}")
            if entry.get("name") == "macroscope":
                if entry.get("source") != "./plugins/macroscope":
                    fail("existing Macroscope marketplace entry has a foreign source")
            else:
                foreign.append(entry)
        marketplace = {**existing, **marketplace, "plugins": [*foreign, *marketplace["plugins"]]}
    market_stage = staged / "marketplace.json"
    market_stage.write_text(json.dumps(marketplace, indent=2) + "\n", encoding="utf-8")
    market_stage.chmod(market_target.stat().st_mode & 0o777 if market_target.exists() else 0o644)
    plugin_stage = staged / "plugin"
    shutil.copytree(root / "plugins/macroscope", plugin_stage)
    targets = [Target(PurePosixPath(".claude-plugin/marketplace.json"), market_stage.name),
               Target(PurePosixPath("plugins/macroscope"), plugin_stage.name)]
    for skill in skills:
        target = output / "skills" / skill.name
        candidate = staged / ("skill-" + skill.name)
        if target.exists():
            check_target(output, target / "SKILL.md")
            ownership = skill_ownership(target / "SKILL.md", skill.name)
            if ownership is None:
                fail(f"unowned standalone skill destination: {target}")
            if ownership == "legacy":
                # Shape alone never authorizes a replacement. A body that leads
                # with the prerequisite block is evidence of an earlier sync, not
                # proof of one, so the operator has to say so for the single
                # migration run; the marker it then writes owns the file outright
                # and no later sync needs the flag.
                if not adopt_unmarked:
                    fail(f"standalone skill destination carries no generated marker: {target}; "
                         "pass --adopt-unmarked to claim a pre-marker sync once")
                print(f"adopting: unmarked standalone skill from an earlier sync: {target}")
            shutil.copytree(target, candidate, symlinks=True)
        else:
            candidate.mkdir()
        # Preserve extra files in an owned skill while updating source resources.
        for source in sorted(skill.rglob("*")):
            relative = source.relative_to(skill)
            check_target(candidate, candidate / relative)
            if source.is_dir():
                (candidate / relative).mkdir(exist_ok=True)
            else:
                shutil.copy2(source, candidate / relative)
        frontmatter, body = skill_frontmatter(skill / "SKILL.md", skill.name)
        (candidate / "SKILL.md").write_text(
            frontmatter + "\n" + GENERATED_MARKER + "\n\n" + PREREQ + "\n" + body,
            encoding="utf-8")
        skill_frontmatter(candidate / "SKILL.md", skill.name)
        targets.append(Target(PurePosixPath("skills") / skill.name, candidate.name))
    return targets


def open_dir(name, dir_fd=None):
    return os.open(name, os.O_RDONLY | os.O_DIRECTORY | os.O_NOFOLLOW, dir_fd=dir_fd)


@contextlib.contextmanager
def deferred_signals():
    """Ignore the termination signals for the duration of a critical section,
    then restore the handlers that were in place.

    Cleanup that is interrupted partway through is worse than cleanup that
    never started: it can remove the transaction and then die before removing
    the lock, and a stranded lock fails every later sync until a human deletes
    it. A signal arriving inside the section is dropped rather than deferred,
    which is the trade being made deliberately: these sections are bounded
    removals of directories this process created, so finishing them is worth
    more than honouring one interrupt."""
    handlers = {number: signal.signal(number, signal.SIG_IGN)
                for number in (signal.SIGINT, signal.SIGTERM, signal.SIGHUP)}
    try:
        yield
    finally:
        for number, handler in handlers.items():
            signal.signal(number, handler)


def remove_tree_at(name, dir_fd):
    """Delete a directory tree named relative to an open directory.

    shutil.rmtree takes a dir_fd only on Python 3.12, and resolving the
    pathname of an ancestor a second time is what these descriptors exist to
    prevent: it would hand an attacker who swapped --output a tree-deletion
    primitive aimed wherever they like."""
    fd = open_dir(name, dir_fd=dir_fd)
    try:
        for entry in list(os.scandir(fd)):
            if entry.is_dir(follow_symlinks=False):
                remove_tree_at(entry.name, fd)
            else:
                os.unlink(entry.name, dir_fd=fd)
    finally:
        os.close(fd)
    os.rmdir(name, dir_fd=dir_fd)


def write_at(name, dir_fd, text):
    with os.fdopen(os.open(name, os.O_CREAT | os.O_EXCL | os.O_WRONLY | os.O_NOFOLLOW, 0o600, dir_fd=dir_fd),
                   "w", encoding="utf-8") as stream:
        stream.write(text)


def make_transaction(output_fd):
    """Create the staging directory relative to the validated output
    descriptor. tempfile.mkdtemp has no dir_fd parameter, so it resolves the
    --output pathname afresh and would place the transaction wherever that
    pathname points by then."""
    while True:
        name = ".macroscope-sync-" + os.urandom(8).hex()
        try:
            os.mkdir(name, 0o700, dir_fd=output_fd)
        except FileExistsError:
            continue
        return name


def exists_at(name, dir_fd):
    try:
        os.lstat(name, dir_fd=dir_fd)
    except FileNotFoundError:
        return False
    return True


def open_parent(output_fd, relative, fds, created):
    # Resolve one component at a time from the validated --output descriptor.
    # O_NOFOLLOW turns a directory swapped for a symlink into ELOOP instead of
    # a rename that lands outside --output.
    fd = output_fd
    for depth, part in enumerate(relative.parts[:-1], start=1):
        try:
            child = open_dir(part, dir_fd=fd)
        except FileNotFoundError:
            os.mkdir(part, dir_fd=fd)
            os.fsync(fd)
            created.append((fd, part))
            child = open_dir(part, dir_fd=fd)
        fds.append(child)
        fd = child
    return fd


def fsync_tree(path):
    # A durable directory entry pointing at unflushed data is still data loss,
    # so staged contents are flushed before any of them is published.
    for item in sorted(path.rglob("*"), reverse=True):
        if item.is_symlink():
            continue
        fd = os.open(item, os.O_RDONLY | (os.O_DIRECTORY if item.is_dir() else 0))
        try:
            os.fsync(fd)
        finally:
            os.close(fd)


def apply_targets(output, targets, transaction, output_fd):
    # os.replace and os.lstat are not listed in their own right; they are
    # renameat and fstatat, so os.rename and os.stat are the probe for both.
    if not {os.open, os.rename, os.stat, os.mkdir, os.rmdir}.issubset(os.supports_dir_fd):
        fail("platform cannot perform race-safe directory-relative replacement")
    staged = transaction / "staged"
    fsync_tree(staged)
    for name in ("backups", "discarded"):
        (transaction / name).mkdir()
    # Retain an explicit recovery map if SIGKILL or a machine shutdown prevents
    # the normal rollback handler from running. The lock blocks a second sync.
    recovery = [{"target": str(output / target.relative), "candidate": str(staged / target.candidate),
                 "backup": str(transaction / "backups" / str(index)),
                 "existed": os.path.lexists(output / target.relative)}
                for index, target in enumerate(targets)]
    with (transaction / "recovery.json").open("w", encoding="utf-8") as stream:
        json.dump(recovery, stream, indent=2)
        stream.write("\n")
        stream.flush()
        os.fsync(stream.fileno())
    journal = []
    created = []
    # Named relative to the descriptor sync validated and has held since before
    # extraction, so no ancestor pathname is resolved a second time here.
    fds = [open_dir(transaction.name, dir_fd=output_fd)]
    try:
        # Durable before the first replacement: a recovery map that survives the
        # crash it describes, and directory entries for the backups it names.
        os.fsync(fds[0])
        staged_fd, backups_fd, discarded_fd = (
            open_dir(name, dir_fd=fds[0]) for name in ("staged", "backups", "discarded"))
        fds += [staged_fd, backups_fd, discarded_fd]
        for index, target in enumerate(targets):
            parent_fd = open_parent(output_fd, target.relative, fds, created)
            name, backup = target.relative.name, str(index)
            existed = exists_at(name, parent_fd)
            # Record before either rename; backup/candidate existence tells us
            # whether an interrupted syscall completed before Python resumed.
            journal.append((parent_fd, target, backup, existed))
            if existed:
                os.replace(name, backup, src_dir_fd=parent_fd, dst_dir_fd=backups_fd)
                os.fsync(backups_fd)
            os.replace(target.candidate, name, src_dir_fd=staged_fd, dst_dir_fd=parent_fd)
            os.fsync(parent_fd)
            os.fsync(staged_fd)
    except BaseException:
        errors = []
        with deferred_signals():
            for parent_fd, target, backup, existed in reversed(journal):
                name = target.relative.name
                try:
                    if exists_at(backup, backups_fd):
                        discard(parent_fd, name, discarded_fd, backup)
                        os.replace(backup, name, src_dir_fd=backups_fd, dst_dir_fd=parent_fd)
                    elif not existed and not exists_at(target.candidate, staged_fd):
                        discard(parent_fd, name, discarded_fd, backup)
                    else:
                        continue
                    os.fsync(parent_fd)
                except OSError as error:
                    errors.append(f"{output / target.relative}: {error}")
            for parent_fd, part in reversed(created):
                try:
                    os.rmdir(part, dir_fd=parent_fd)
                    os.fsync(parent_fd)
                except OSError:
                    pass
        if errors:
            raise RuntimeError("rollback incomplete; retained recovery files at "
                               + str(transaction) + ": " + "; ".join(errors))
        raise
    finally:
        for fd in dict.fromkeys(fds):
            os.close(fd)


def discard(parent_fd, name, discarded_fd, slot):
    # rename cannot replace a non-empty directory and rmtree would resolve the
    # pathname again, so an entry is retired by moving it into the transaction.
    try:
        os.replace(name, slot, src_dir_fd=parent_fd, dst_dir_fd=discarded_fd)
    except FileNotFoundError:
        pass


def sync(repo, ref, output, adopt_unmarked=False):
    repo = Path(repo).resolve(strict=True)
    output = Path(output).absolute()
    if output.is_symlink() or not output.is_dir():
        fail("--output must be an existing directory, not a symlink")
    output = output.resolve()
    if output == Path(output.anchor) or output == Path.home().resolve() or output == repo or repo in output.parents:
        fail("unsafe output directory: choose a separate release checkout or temporary directory")
    # Hold the validated directory open before the slow work below. Extracting
    # the source runs git and tar for seconds, and every check above is stale
    # the moment it returns; naming the lock, the transaction and their removal
    # relative to this descriptor means replacing the --output pathname with a
    # symlink in that window cannot relocate any of them.
    output_fd = open_dir(str(output))
    try:
        with tempfile.TemporaryDirectory(prefix="macroscope-sync-source-") as source_dir:
            root, resolved = extract_source(repo, ref, Path(source_dir))
            marketplace, skills, version = validate_bundle(root)
            try:
                os.mkdir(LOCK_NAME, 0o700, dir_fd=output_fd)
            except FileExistsError:
                fail(f"sync lock exists; another sync or interrupted recovery owns {output / LOCK_NAME}")
            transaction_name = None
            keep_recovery = False
            try:
                transaction_name = make_transaction(output_fd)
                transaction = output / transaction_name
                lock_fd = open_dir(LOCK_NAME, dir_fd=output_fd)
                try:
                    write_at("owner.json", lock_fd, json.dumps({"pid": os.getpid(), "sourceRef": resolved,
                                                                "transaction": str(transaction)}) + "\n")
                finally:
                    os.close(lock_fd)
                targets = prepare_targets(root, output, transaction, marketplace, skills, adopt_unmarked)
                try:
                    apply_targets(output, targets, transaction, output_fd)
                except RuntimeError:
                    keep_recovery = True
                    raise
                for target in targets:
                    print(f"synced: {target.relative}")
                print(f"done: source {resolved}, plugin {version}, {len(skills)} standalone skill(s)")
            finally:
                # Removing the transaction and releasing the lock is one
                # indivisible step. A signal landing between them strands the
                # lock, and a stranded lock fails every later sync.
                if not keep_recovery:
                    with deferred_signals():
                        if transaction_name is not None:
                            remove_tree_at(transaction_name, output_fd)
                        remove_tree_at(LOCK_NAME, output_fd)
    finally:
        os.close(output_fd)


def interrupted(signum, _frame):
    raise InterruptedError(f"sync interrupted by signal {signum}")


def main(argv, default_output):
    parser = argparse.ArgumentParser(description="Sync a pinned public-plugin bundle, preserving unrelated plugins and skills.")
    parser.add_argument("back_repo")
    parser.add_argument("--ref", required=True, help="full source commit SHA; dirty files are ignored")
    parser.add_argument("--output", default=str(default_output), help="existing output directory (default: script repository)")
    parser.add_argument("--adopt-unmarked", action="store_true",
                        help="claim standalone skills written before the generated marker existed; needed once per checkout")
    args = parser.parse_args(argv)
    for sig in (signal.SIGINT, signal.SIGTERM, signal.SIGHUP):
        signal.signal(sig, interrupted)
    try:
        sync(args.back_repo, args.ref, args.output, args.adopt_unmarked)
    except (OSError, ValueError, RuntimeError, subprocess.CalledProcessError, tarfile.TarError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[2:], Path(sys.argv[1])))
PY
