#!/bin/bash
set -euo pipefail

# Sync a committed bundle, retaining unrelated plugins, skills, and registrations.
# Usage: sync-skills-from-back.sh /path/to/back --ref FULL_SHA [--output DIR]
# --output must already exist. Use a temporary directory for release rehearsals.
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
exec python3 - "$SCRIPT_DIR/.." "$@" <<'PY'
import argparse
import json
import os
from pathlib import Path, PurePosixPath
import re
import shutil
import signal
import subprocess
import sys
import tarfile
import tempfile

SOURCE_PREFIX = "tools/cmd/macrodaemon/public-plugin"
REPOSITORY = "https://github.com/prassoai/macroscope-local"
GENERATED_MARKER = "<!-- Generated by sync-skills-from-back.sh. -->"
PREREQ = """## 0. Verify the CLI is installed

```bash
command -v macroscope
```

If `macroscope` is not found, tell the user:

> Macroscope CLI is not installed. Install it with:
>
> ```bash
> curl -sSL https://raw.githubusercontent.com/prassoai/macroscope-local/main/install.sh | bash
> ```

Stop here if the CLI is missing.
"""


def fail(message):
    raise ValueError(message)


def git(repo, *arguments, **kwargs):
    # Caller worktree/index overrides must not change which repository is read.
    env = {key: value for key, value in os.environ.items() if not key.startswith("GIT_")}
    env["GIT_CONFIG_NOSYSTEM"] = "1"
    return subprocess.run(["git", "--no-optional-locks", "-C", str(repo), *arguments],
                          env=env, check=True, stderr=subprocess.PIPE, **kwargs)


def read_json(path):
    with path.open(encoding="utf-8") as stream:
        data = json.load(stream)
    if not isinstance(data, dict):
        fail(f"expected a JSON object: {path}")
    return data


def extract_source(repo, ref, stage):
    if not re.fullmatch(r"[0-9a-fA-F]{40}", ref):
        fail("--ref must be a full 40-character commit SHA")
    resolved = git(repo, "rev-parse", "--verify", ref + "^{commit}",
                   stdout=subprocess.PIPE, text=True).stdout.strip()
    if resolved != ref.lower():
        fail("--ref did not resolve to the requested commit")
    archive = stage / "source.tar"
    with archive.open("wb") as stream:
        git(repo, "archive", "--format=tar", resolved, "--", SOURCE_PREFIX, stdout=stream)
    root = stage / "source"
    root.mkdir()
    prefix = PurePosixPath(SOURCE_PREFIX).parts
    with tarfile.open(archive, "r:") as bundle:
        for member in bundle:
            name = PurePosixPath(member.name)
            if name.is_absolute() or ".." in name.parts:
                fail(f"unsafe source path: {member.name}")
            if name.parts == prefix[:len(name.parts)] and member.isdir():
                continue
            if name.parts[:len(prefix)] != prefix or not (member.isfile() or member.isdir()):
                fail(f"unsupported source archive entry: {member.name}")
            target = root.joinpath(*name.parts[len(prefix):])
            if member.isdir():
                target.mkdir(parents=True, exist_ok=True)
            else:
                target.parent.mkdir(parents=True, exist_ok=True)
                with bundle.extractfile(member) as source, target.open("xb") as dest:
                    shutil.copyfileobj(source, dest)
                target.chmod(0o755 if member.mode & 0o111 else 0o644)
    return root, resolved


def skill_frontmatter(path, name):
    lines = path.read_text(encoding="utf-8").splitlines(keepends=True)
    if not lines or lines[0].strip() != "---":
        fail(f"missing skill frontmatter: {path}")
    closing = next((i for i in range(1, len(lines)) if lines[i].strip() == "---"), None)
    if closing is None:
        fail(f"unterminated skill frontmatter: {path}")
    header = "".join(lines[1:closing])
    if not re.search(r"(?m)^name:\s*[\"']?" + re.escape(name) + r"[\"']?\s*$", header):
        fail(f"incorrect skill name: {path}")
    if not re.search(r"(?m)^description:\s*\S", header) or not "".join(lines[closing + 1:]).strip():
        fail(f"incomplete skill: {path}")
    return "".join(lines[:closing + 1]), "".join(lines[closing + 1:]).lstrip("\r\n")


def validate_bundle(root):
    plugin = root / "plugins/macroscope"
    marketplace = read_json(root / ".claude-plugin/marketplace.json")
    manifests = [read_json(plugin / host / "plugin.json")
                 for host in (".claude-plugin", ".codex-plugin", ".cursor-plugin")]
    version = manifests[0].get("version", "")
    if not isinstance(version, str) or not re.fullmatch(r"\d+\.\d+\.\d+(?:[-+][A-Za-z0-9.-]+)?", version):
        fail("plugin version must be a safe semantic version")
    if any(item.get("name") != "macroscope" or item.get("version") != version for item in manifests):
        fail("host plugin manifests disagree on name or version")
    entries = marketplace.get("plugins")
    if (marketplace.get("name") != "macroscope-local" or not isinstance(entries, list)
            or len(entries) != 1 or not isinstance(entries[0], dict)
            or entries[0].get("name") != "macroscope"
            or entries[0].get("source") != "./plugins/macroscope"
            or entries[0].get("version") != version):
        fail("source marketplace must match the Macroscope plugin and version")
    for relative in ("commands/macroscope-codereview.md", "commands/macroscope-autoloop.md",
                     "opencode/macroscope.js", "assets/macroscope.svg", "assets/macroscope-small.svg"):
        path = plugin / relative
        if not path.is_file() or path.stat().st_size == 0:
            fail(f"missing or empty plugin asset: {relative}")
    skills = sorted((plugin / "skills").iterdir())
    if not {"codereview", "autoloop"}.issubset({item.name for item in skills}):
        fail("source bundle must include codereview and autoloop skills")
    for skill in skills:
        if not skill.is_dir() or not re.fullmatch(r"[a-z0-9][a-z0-9-]*", skill.name):
            fail(f"invalid skill directory: {skill}")
        skill_frontmatter(skill / "SKILL.md", skill.name)
    for host in ("claude", "codex"):
        for name in ("codereview", "autoloop"):
            skill_frontmatter(plugin / "host-overlays" / host / "skills" / name / "SKILL.md", name)
    return marketplace, skills, version


def check_target(output, target):
    for path in (target, *target.parents):
        if path == output:
            break
        if path.is_symlink():
            fail(f"refusing to replace or traverse a destination symlink: {path}")
        if path != target and path.exists() and not path.is_dir():
            fail(f"destination parent is not a directory: {path}")


def prepare_targets(root, output, transaction, marketplace, skills):
    staged = transaction / "staged"
    staged.mkdir()
    plugin_target = output / "plugins/macroscope"
    market_target = output / ".claude-plugin/marketplace.json"
    for target in (plugin_target, market_target, *(output / "skills" / skill.name for skill in skills)):
        check_target(output, target)
    if plugin_target.exists():
        existing = read_json(plugin_target / ".claude-plugin/plugin.json")
        if existing.get("name") != "macroscope" or existing.get("repository") != REPOSITORY:
            fail(f"unowned plugin destination: {plugin_target}")
    if market_target.exists():
        existing = read_json(market_target)
        if existing.get("name") != marketplace["name"] or not isinstance(existing.get("plugins"), list):
            fail(f"unowned marketplace destination: {market_target}")
        foreign = []
        for entry in existing["plugins"]:
            if not isinstance(entry, dict):
                fail(f"invalid existing marketplace entry: {market_target}")
            if entry.get("name") == "macroscope":
                if entry.get("source") != "./plugins/macroscope":
                    fail("existing Macroscope marketplace entry has a foreign source")
            else:
                foreign.append(entry)
        marketplace = {**existing, **marketplace, "plugins": [*foreign, *marketplace["plugins"]]}
    market_stage = staged / "marketplace.json"
    market_stage.write_text(json.dumps(marketplace, indent=2) + "\n", encoding="utf-8")
    market_stage.chmod(market_target.stat().st_mode & 0o777 if market_target.exists() else 0o644)
    plugin_stage = staged / "plugin"
    shutil.copytree(root / "plugins/macroscope", plugin_stage)
    targets = [(market_target, market_stage), (plugin_target, plugin_stage)]
    for skill in skills:
        target = output / "skills" / skill.name
        candidate = staged / ("skill-" + skill.name)
        if target.exists():
            check_target(output, target / "SKILL.md")
            old_text = (target / "SKILL.md").read_text(encoding="utf-8")
            if GENERATED_MARKER not in old_text and PREREQ not in old_text:
                fail(f"unowned standalone skill destination: {target}")
            shutil.copytree(target, candidate, symlinks=True)
        else:
            candidate.mkdir()
        # Preserve extra files in an owned skill while updating source resources.
        for source in sorted(skill.rglob("*")):
            relative = source.relative_to(skill)
            check_target(candidate, candidate / relative)
            if source.is_dir():
                (candidate / relative).mkdir(exist_ok=True)
            else:
                shutil.copy2(source, candidate / relative)
        frontmatter, body = skill_frontmatter(skill / "SKILL.md", skill.name)
        (candidate / "SKILL.md").write_text(
            frontmatter + "\n" + GENERATED_MARKER + "\n\n" + PREREQ + "\n" + body,
            encoding="utf-8")
        skill_frontmatter(candidate / "SKILL.md", skill.name)
        targets.append((target, candidate))
    return targets


def remove_path(path):
    if path.is_dir() and not path.is_symlink():
        shutil.rmtree(path)
    elif os.path.lexists(path):
        path.unlink()


def apply_targets(targets, transaction):
    backups = transaction / "backups"
    backups.mkdir()
    # Retain an explicit recovery map if SIGKILL or a machine shutdown prevents
    # the normal rollback handler from running. The lock blocks a second sync.
    recovery = [{"target": str(target), "candidate": str(candidate),
                 "backup": str(backups / str(index)), "existed": os.path.lexists(target)}
                for index, (target, candidate) in enumerate(targets)]
    with (transaction / "recovery.json").open("w", encoding="utf-8") as stream:
        json.dump(recovery, stream, indent=2)
        stream.write("\n")
        stream.flush()
        os.fsync(stream.fileno())
    journal = []
    new_parents = []
    try:
        for index, (target, candidate) in enumerate(targets):
            missing = []
            parent = target.parent
            while not parent.exists():
                missing.append(parent)
                parent = parent.parent
            for parent in reversed(missing):
                parent.mkdir()
                new_parents.append(parent)
            backup = backups / str(index)
            existed = os.path.lexists(target)
            # Record before either rename; backup/candidate existence tells us
            # whether an interrupted syscall completed before Python resumed.
            journal.append((target, candidate, backup, existed))
            if existed:
                os.replace(target, backup)
            os.replace(candidate, target)
    except BaseException:
        handlers = {sig: signal.signal(sig, signal.SIG_IGN)
                    for sig in (signal.SIGINT, signal.SIGTERM, signal.SIGHUP)}
        errors = []
        try:
            for target, candidate, backup, existed in reversed(journal):
                try:
                    if os.path.lexists(backup):
                        remove_path(target)
                        os.replace(backup, target)
                    elif not existed and not os.path.lexists(candidate):
                        remove_path(target)
                except OSError as error:
                    errors.append(f"{target}: {error}")
            for parent in reversed(new_parents):
                try:
                    parent.rmdir()
                except OSError:
                    pass
        finally:
            for sig, handler in handlers.items():
                signal.signal(sig, handler)
        if errors:
            raise RuntimeError("rollback incomplete; retained recovery files at "
                               + str(transaction) + ": " + "; ".join(errors))
        raise


def sync(repo, ref, output):
    repo = Path(repo).resolve(strict=True)
    output = Path(output).absolute()
    if output.is_symlink() or not output.is_dir():
        fail("--output must be an existing directory, not a symlink")
    output = output.resolve()
    if output == Path(output.anchor) or output == Path.home().resolve() or output == repo or repo in output.parents:
        fail("unsafe output directory: choose a separate release checkout or temporary directory")
    with tempfile.TemporaryDirectory(prefix="macroscope-sync-source-") as source_dir:
        root, resolved = extract_source(repo, ref, Path(source_dir))
        marketplace, skills, version = validate_bundle(root)
        lock = output / ".macroscope-sync.lock"
        try:
            lock.mkdir(mode=0o700)
        except FileExistsError:
            fail(f"sync lock exists; another sync or interrupted recovery owns {lock}")
        transaction = None
        keep_recovery = False
        try:
            transaction = Path(tempfile.mkdtemp(prefix=".macroscope-sync-", dir=output))
            (lock / "owner.json").write_text(json.dumps({"pid": os.getpid(), "sourceRef": resolved,
                                                       "transaction": str(transaction)}) + "\n")
            targets = prepare_targets(root, output, transaction, marketplace, skills)
            try:
                apply_targets(targets, transaction)
            except RuntimeError:
                keep_recovery = True
                raise
            for target, _ in targets:
                print(f"synced: {target.relative_to(output)}")
            print(f"done: source {resolved}, plugin {version}, {len(skills)} standalone skill(s)")
        finally:
            if not keep_recovery:
                if transaction is not None:
                    shutil.rmtree(transaction)
                shutil.rmtree(lock)


def interrupted(signum, _frame):
    raise InterruptedError(f"sync interrupted by signal {signum}")


def main(argv, default_output):
    parser = argparse.ArgumentParser(description="Sync a pinned public-plugin bundle, preserving unrelated plugins and skills.")
    parser.add_argument("back_repo")
    parser.add_argument("--ref", required=True, help="full source commit SHA; dirty files are ignored")
    parser.add_argument("--output", default=str(default_output), help="existing output directory (default: script repository)")
    args = parser.parse_args(argv)
    for sig in (signal.SIGINT, signal.SIGTERM, signal.SIGHUP):
        signal.signal(sig, interrupted)
    try:
        sync(args.back_repo, args.ref, args.output)
    except (OSError, ValueError, RuntimeError, subprocess.CalledProcessError, tarfile.TarError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[2:], Path(sys.argv[1])))
PY
